// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GPostgreSQLExample.Repositories.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace GPostgreSQLExample.Repositories.Entities.Configurations
{
    public partial class PlayerInfoConfiguration : IEntityTypeConfiguration<PlayerInfo>
    {
        public void Configure(EntityTypeBuilder<PlayerInfo> entity)
        {
            entity.HasKey(e => e.PlayerId)
                .HasName("playerinfos_pk");

            entity.Property(e => e.PlayerId).ValueGeneratedNever();

            entity.HasOne(d => d.Player)
                .WithOne(p => p.PlayerInfo)
                .HasForeignKey<PlayerInfo>(d => d.PlayerId)
                .HasConstraintName("playerinfos_fk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlayerInfo> entity);
    }
}
