// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GPostgreSQLExample.Repositories.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace GPostgreSQLExample.Repositories.Entities.Configurations
{
    public partial class PlayerRecordConfiguration : IEntityTypeConfiguration<PlayerRecord>
    {
        public void Configure(EntityTypeBuilder<PlayerRecord> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlayerRecord> entity);
    }
}
