// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GPostgreSQLExample.Repositories.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace GPostgreSQLExample.Repositories.Entities.Configurations
{
    public partial class PlayerConfiguration : IEntityTypeConfiguration<Player>
    {
        public void Configure(EntityTypeBuilder<Player> entity)
        {
            entity.Property(e => e.PlayerId).ValueGeneratedNever();

            entity.Property(e => e.CreateTime).HasDefaultValueSql("now()");

            entity.Property(e => e.ModifyTime).HasDefaultValueSql("now()");

            entity.Property(e => e.Status).HasComment("狀態(0:停用、1:啟用、2:鎖住)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Player> entity);
    }
}
