// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace GPostgreSQLExample.Repositories.Entities
{
    [Table("playerRecords", Schema = "main")]
    public partial class PlayerRecord
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("player_id")]
        public Guid PlayerId { get; set; }
        [Required]
        [Column("old_data", TypeName = "jsonb")]
        public string OldData { get; set; } = default!;
        [Required]
        [Column("new_data", TypeName = "jsonb")]
        public string NewData { get; set; } = default!;
        [Column("create_time", TypeName = "timestamp with time zone")]
        public DateTime CreateTime { get; set; }
    }
}