// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace GPostgreSQLExample.Repositories.Entities
{
    [Table("PlayerInfos", Schema = "main")]
    public partial class PlayerInfo
    {
        [Key]
        [Column("player_id")]
        public Guid PlayerId { get; set; }
        [Column("last_name")]
        [StringLength(32)]
        public string? LastName { get; set; }
        [Column("full_name")]
        [StringLength(32)]
        public string? FullName { get; set; }
        [Column("nick_name")]
        [StringLength(32)]
        public string? NickName { get; set; }
        [Column("phone_number")]
        [StringLength(20)]
        public string? PhoneNumber { get; set; }
        [Column("mailbox")]
        [StringLength(128)]
        public string? Mailbox { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("PlayerInfo")]
        public virtual Player Player { get; set; } = default!;
    }
}