// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace GPostgreSQLExample.Repositories.Entities
{
    [Table("players", Schema = "main")]
    [Index(nameof(Account), Name = "players_account_idx", IsUnique = true)]
    public partial class Player
    {
        [Key]
        [Column("player_id")]
        public Guid PlayerId { get; set; }
        [Required]
        [Column("account")]
        [StringLength(32)]
        public string Account { get; set; } = default!;
        [Required]
        [Column("password")]
        [StringLength(128)]
        public string Password { get; set; } = default!;
        [Column("create_time", TypeName = "timestamp with time zone")]
        public DateTime CreateTime { get; set; }
        [Column("modify_time", TypeName = "timestamp with time zone")]
        public DateTime ModifyTime { get; set; }
        /// <summary>
        /// 狀態(0:停用、1:啟用、2:鎖住)
        /// </summary>
        [Column("status")]
        public short Status { get; set; }

        [InverseProperty("Player")]
        public virtual PlayerInfo PlayerInfo { get; set; } = default!;
    }
}